-- Numeris production schema and RLS policies.
-- Apply from the Supabase SQL editor or Supabase CLI.

create extension if not exists pgcrypto;

create table if not exists public.numeris_modules (
  id bigint generated by default as identity primary key,
  name text not null,
  domain text not null,
  description text not null,
  status text not null default 'ACTIVE',
  metric integer not null default 0 check (metric between 0 and 100),
  gradient text not null default 'linear-gradient(135deg,#06b6d4,#8b5cf6)',
  depth integer not null default 1
);

create table if not exists public.numeris_signals (
  id bigint generated by default as identity primary key,
  symbol text not null,
  verdict text not null check (verdict in ('BUY','SELL','HOLD')),
  confidence integer not null check (confidence between 0 and 100),
  momentum integer not null check (momentum between 0 and 100),
  risk integer not null check (risk between 0 and 100),
  agent text not null,
  price numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.numeris_simulations (
  id bigint generated by default as identity primary key,
  name text not null,
  engine text not null,
  region text not null,
  intensity integer not null default 50 check (intensity between 0 and 100),
  forecast text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.numeris_reports (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  severity text not null default 'LOW',
  summary text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.numeris_event_stream (
  id bigint generated by default as identity primary key,
  event_type text not null,
  title text not null,
  detail text not null,
  impact integer not null default 0 check (impact between 0 and 100),
  region text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.numeris_brain_traits (
  id bigint generated by default as identity primary key,
  label text not null,
  value integer not null default 0 check (value between 0 and 100),
  color text not null default '#06b6d4',
  priority integer not null default 1
);

create table if not exists public.numeris_brain_regions (
  id bigint generated by default as identity primary key,
  name text not null,
  system text not null,
  description text not null,
  section_id text not null,
  x numeric not null check (x between 0 and 100),
  y numeric not null check (y between 0 and 100),
  position_order integer not null default 1
);

create table if not exists public.numeris_entrance_sequences (
  id bigint generated by default as identity primary key,
  label text not null,
  value text not null,
  sequence_order integer not null default 1
);

create table if not exists public.numeris_geopolitical_news (
  id bigint generated by default as identity primary key,
  title text not null,
  source text not null,
  url text not null,
  region text not null,
  impact integer not null default 0 check (impact between 0 and 100),
  summary text not null,
  published_at timestamptz not null default now(),
  fetched_at timestamptz not null default now()
);

create table if not exists public.numeris_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  prompt text not null,
  response text not null,
  agent text not null,
  confidence integer not null default 0 check (confidence between 0 and 100),
  created_at timestamptz not null default now()
);

create table if not exists public.numeris_manual_portfolio (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  quantity numeric not null check (quantity > 0),
  avg_price numeric not null check (avg_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, symbol)
);

create table if not exists public.numeris_analysis_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  symbol text,
  response_summary text,
  agents_used jsonb not null default '[]'::jsonb,
  confidence_score numeric,
  recommendation text,
  full_response_path text,
  processing_time_ms integer,
  created_at timestamptz not null default now()
);

create table if not exists public.numeris_shared_cache (
  id uuid primary key default gen_random_uuid(),
  symbol text not null,
  data_type text not null,
  data jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.numeris_user_backups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists numeris_manual_portfolio_user_idx on public.numeris_manual_portfolio(user_id);
create index if not exists numeris_interactions_user_idx on public.numeris_interactions(user_id, created_at desc);
create index if not exists numeris_shared_cache_lookup_idx on public.numeris_shared_cache(symbol, data_type, created_at desc);

alter table public.numeris_modules enable row level security;
alter table public.numeris_signals enable row level security;
alter table public.numeris_simulations enable row level security;
alter table public.numeris_reports enable row level security;
alter table public.numeris_event_stream enable row level security;
alter table public.numeris_brain_traits enable row level security;
alter table public.numeris_brain_regions enable row level security;
alter table public.numeris_entrance_sequences enable row level security;
alter table public.numeris_geopolitical_news enable row level security;
alter table public.numeris_interactions enable row level security;
alter table public.numeris_manual_portfolio enable row level security;
alter table public.numeris_analysis_history enable row level security;
alter table public.numeris_shared_cache enable row level security;
alter table public.numeris_user_backups enable row level security;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'numeris_modules',
    'numeris_signals',
    'numeris_simulations',
    'numeris_reports',
    'numeris_event_stream',
    'numeris_brain_traits',
    'numeris_brain_regions',
    'numeris_entrance_sequences',
    'numeris_geopolitical_news'
  ]
  loop
    execute format('drop policy if exists "%s_public_read" on public.%I', table_name, table_name);
    execute format('create policy "%s_public_read" on public.%I for select using (true)', table_name, table_name);
  end loop;
end $$;

drop policy if exists "numeris_manual_portfolio_owner_select" on public.numeris_manual_portfolio;
create policy "numeris_manual_portfolio_owner_select"
on public.numeris_manual_portfolio for select
using (auth.uid() = user_id);

drop policy if exists "numeris_manual_portfolio_owner_insert" on public.numeris_manual_portfolio;
create policy "numeris_manual_portfolio_owner_insert"
on public.numeris_manual_portfolio for insert
with check (auth.uid() = user_id);

drop policy if exists "numeris_manual_portfolio_owner_update" on public.numeris_manual_portfolio;
create policy "numeris_manual_portfolio_owner_update"
on public.numeris_manual_portfolio for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "numeris_manual_portfolio_owner_delete" on public.numeris_manual_portfolio;
create policy "numeris_manual_portfolio_owner_delete"
on public.numeris_manual_portfolio for delete
using (auth.uid() = user_id);

drop policy if exists "numeris_interactions_owner_read" on public.numeris_interactions;
create policy "numeris_interactions_owner_read"
on public.numeris_interactions for select
using (user_id is null or auth.uid() = user_id);

drop policy if exists "numeris_analysis_owner_read" on public.numeris_analysis_history;
create policy "numeris_analysis_owner_read"
on public.numeris_analysis_history for select
using (auth.uid() = user_id);

drop policy if exists "numeris_backups_owner_read" on public.numeris_user_backups;
create policy "numeris_backups_owner_read"
on public.numeris_user_backups for select
using (auth.uid() = user_id);

-- One-time legacy data copy from AI-generated table names when they exist.
do $$
declare
  legacy text;
  target text;
begin
  for legacy, target in
    select * from (values
      ('quantmind_modules','numeris_modules'),
      ('quantmind_signals','numeris_signals'),
      ('quantmind_simulations','numeris_simulations'),
      ('quantmind_reports','numeris_reports'),
      ('quantmind_event_stream','numeris_event_stream'),
      ('quantmind_brain_traits','numeris_brain_traits'),
      ('quantmind_brain_regions','numeris_brain_regions'),
      ('quantmind_entrance_sequences','numeris_entrance_sequences'),
      ('quantmind_geopolitical_news','numeris_geopolitical_news')
    ) as mappings(legacy, target)
  loop
    if to_regclass('public.' || legacy) is not null then
      execute format('insert into public.%I select * from public.%I on conflict do nothing', target, legacy);
    end if;
  end loop;
end $$;
